SET IDENTITY_INSERT [dbo].[Tests] OFF
INSERT INTO [dbo].[Tests] ([TaskId], [Input], [Output]) VALUES (1, N'5 3',  N'8')
INSERT INTO [dbo].[Tests] ([TaskId], [Input], [Output]) VALUES (1, N'0 -5', N'-5')
INSERT INTO [dbo].[Tests] ([TaskId], [Input], [Output]) VALUES (2, N'4 -5', N'-20')
INSERT INTO [dbo].[Tests] ([TaskId], [Input], [Output]) VALUES (2, N'0 5',  N'0')
INSERT INTO [dbo].[Tests] ([TaskId], [Input], [Output]) VALUES (4, N'1 15 3', N'18')
INSERT INTO [dbo].[Tests] ([TaskId], [Input], [Output]) VALUES (4, N'1 0 5', N'5')
INSERT INTO [dbo].[Tests] ([TaskId], [Input], [Output]) VALUES (5, N'0 8',   N'0')
INSERT INTO [dbo].[Tests] ([TaskId], [Input], [Output]) VALUES (5, N'3 27',  N'9')
INSERT INTO [dbo].[Tests] ([TaskId], [Input], [Output]) VALUES (7, N'100',   N'2')
INSERT INTO [dbo].[Tests] ([TaskId], [Input], [Output]) VALUES (7, N'1',     N'0')
INSERT INTO [dbo].[Tests] ([TaskId], [Input], [Output]) VALUES (9, N'7 -6',  N'35')
INSERT INTO [dbo].[Tests] ([TaskId], [Input], [Output]) VALUES (9, N'3 21',  N'60')
INSERT INTO [dbo].[Tests] ([TaskId], [Input], [Output]) VALUES (13, N'3 8 5 2', N'240')
INSERT INTO [dbo].[Tests] ([TaskId], [Input], [Output]) VALUES (13, N'3 12 0 2', N'0')
